/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ducho' at '12/13/16 2:31 PM' with Gradle 2.14.1
 *
 * @author ducho, @date 12/13/16 2:31 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
